### PR TITLE
Expand Go SDK docs in developer portal

### PR DESCRIPTION
**Pull request by nullstyle**
This PR integrates documentation defined in our monorepo into the developers portal.

### CODE REVIEW

**Comment by bartekn** [comment]
This breaks a build:
```
[15:04:57] Starting 'src:symlink-repos'...
[15:04:57] gulp-sym: ../repos/horizon/docs → /app/src/horizon
[15:04:57] gulp-sym: ../repos/interstellar/docs → /app/src/interstellar
[15:04:57] gulp-sym: ../repos/js-stellar-base/docs → /app/src/js-stellar-base
[15:04:57] gulp-sym: ../repos/js-stellar-sdk/docs → /app/src/js-stellar-sdk
[15:04:57] gulp-sym: ../repos/stellar-core/docs → /app/src/stellar-core
[15:04:57] Finished 'src:symlink-repos' after 105 ms
[15:04:57] Starting 'build'...
[15:04:58] 'build' errored after 518 ms
[15:04:58] Error: ENOENT: no such file or directory, stat '/app/src/go'
    at Error (native)
rolling back
chown: cannot access './build': No such file or directory
rolling back
rm: cannot remove 'build-node.bash': No such file or directory
rm: cannot remove 'build-node.bash': No such file or directory
rolling back
rm: cannot remove 'build-node.bash': No such file or directory
sending incremental file list
rsync: change_dir "/var/lib/jenkins/jobs/stellar-developers/workspace//./build" failed: No such file or directory (2)

sent 20 bytes  received 12 bytes  64.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.0]
Build step 'Execute shell' marked build as failure
Notifying upstream projects of job completion
Finished: FAILURE
```

**Comment by nullstyle** [comment]
Not sure why the go  repo isn't being cloned... checking into it now

**Comment by nullstyle** [comment]
Looks like it was just because the addition of the docs folder to the monorepo hadn't been merged

**Comment by bartekn** [comment]
OK, it's working now. Thanks!

**Pull request merged**
